#!/usr/bin/env bash
# Read-only AT1b supply+poll harness cron status.
# Prints last_run_at / next_run_at / enabled for the two known prod harnesses.
# Never PATCHes; never prints secrets.
#
# Usage:
#   ./scripts/at1b-harness-status.sh
#   ./scripts/at1b-harness-status.sh --write-report
#
# Credentials:
#   AT_ORBITA_API_KEY + AT_ORBITA_CLIENT_ID  (preferred)
#   ORBITA_API_KEY + ORBITA_CLIENT_ID
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AT_AGENT="$ROOT/at-agent"
WRITE_REPORT=false
[[ "${1:-}" == "--write-report" ]] && WRITE_REPORT=true

# Source gitignored env files; never echo their contents.
if [[ -f "$AT_AGENT/.env.local" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$AT_AGENT/.env.local"
  set +a
elif [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
elif [[ -f "$HOME/.orbita-personal.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$HOME/.orbita-personal.env"
  set +a
fi

: "${ORBITA_API_BASE:=${ORBITA_API_URL:-https://api.get-orbita.com}}"

API_KEY="${AT_ORBITA_API_KEY:-${ORBITA_API_KEY:-}}"
CLIENT_ID="${AT_ORBITA_CLIENT_ID:-${ORBITA_CLIENT_ID:-content-ai-transformation-org}}"

SUPPLY_ID="${AT_SUPPLY_HARNESS_ID:-dd839025-1200-4df4-b69b-b3454625416f}"
POLL_ID="${AT_POLL_HARNESS_ID:-e4c0de60-9db6-4bb8-9845-b5c586afcc36}"

if [[ -z "$API_KEY" ]]; then
  echo "error: missing credentials — set AT_ORBITA_API_KEY (or ORBITA_API_KEY) in at-agent/.env.local, .env, or ~/.orbita-personal.env" >&2
  exit 1
fi

fetch_harness() {
  local id="$1"
  local label="$2"
  local url="${ORBITA_API_BASE%/}/v1/harnesses/${id}"
  local body http_code
  body=$(curl -4 -sS -w "\n%{http_code}" \
    -H "Authorization: Bearer ${API_KEY}" \
    -H "x-orbita-client-id: ${CLIENT_ID}" \
    -H "Accept: application/json" \
    "$url") || {
    echo "error: request failed for ${label} (${id})" >&2
    exit 1
  }
  http_code=$(printf '%s' "$body" | tail -n1)
  body=$(printf '%s' "$body" | sed '$d')
  if [[ "$http_code" != "200" ]]; then
    echo "error: GET harness ${label} (${id}) → HTTP ${http_code}" >&2
    exit 1
  fi
  LABEL="$label" HARNESS_ID="$id" python3 -c '
import json, os, sys
data = json.loads(sys.stdin.read())
h = data.get("harness") or data
print(json.dumps({
  "label": os.environ["LABEL"],
  "id": h.get("id") or os.environ["HARNESS_ID"],
  "name": h.get("name"),
  "enabled": h.get("enabled"),
  "cron": h.get("cron"),
  "timezone": h.get("timezone"),
  "last_run_at": h.get("last_run_at"),
  "next_run_at": h.get("next_run_at"),
}, ensure_ascii=False))
' <<<"$body"
}

SUPPLY_JSON=$(fetch_harness "$SUPPLY_ID" "supply")
POLL_JSON=$(fetch_harness "$POLL_ID" "poll")

STATUS_RC=0
python3 - "$SUPPLY_JSON" "$POLL_JSON" <<'PY' || STATUS_RC=$?
import json, sys
from datetime import datetime, timezone

rows = [json.loads(sys.argv[1]), json.loads(sys.argv[2])]
now = datetime.now(timezone.utc)

def parse_iso(s):
    if not s:
        return None
    return datetime.fromisoformat(s.replace("Z", "+00:00"))

print("AT1b harness cron status (read-only)")
print(f"checked_at_utc: {now.strftime('%Y-%m-%dT%H:%M:%SZ')}")
print("")
for r in rows:
    last = parse_iso(r.get("last_run_at"))
    age = ""
    if last:
        hrs = (now - last).total_seconds() / 3600.0
        age = f"  (age≈{hrs:.1f}h)"
    print(f"[{r['label']}] {r.get('name') or ''}  id={r['id']}")
    print(f"  enabled:     {r.get('enabled')}")
    print(f"  cron:        {r.get('cron')}  tz={r.get('timezone')}")
    print(f"  last_run_at: {r.get('last_run_at')}{age}")
    print(f"  next_run_at: {r.get('next_run_at')}")
    print("")

# Freshness: supply ~07:00 UTC, poll ~18:00 UTC → stale if last_run > 36h
stale = []
for r in rows:
    last = parse_iso(r.get("last_run_at"))
    if r.get("enabled") is False:
        stale.append(f"{r['label']}: disabled")
    elif last is None:
        stale.append(f"{r['label']}: never ran")
    elif (now - last).total_seconds() > 36 * 3600:
        stale.append(f"{r['label']}: last_run older than 36h")

if stale:
    print("freshness: STALE — " + "; ".join(stale))
    sys.exit(2)
print("freshness: OK (both harnesses ran within ~36h and enabled)")
PY

if [[ "$WRITE_REPORT" == "true" ]]; then
  REPORT="$ROOT/docs/at-harness-status.md"
  python3 - "$SUPPLY_JSON" "$POLL_JSON" "$REPORT" "$SUPPLY_ID" "$POLL_ID" <<'PY'
import json, sys
from datetime import datetime, timezone
from pathlib import Path

rows = [json.loads(sys.argv[1]), json.loads(sys.argv[2])]
path = Path(sys.argv[3])
supply_id, poll_id = sys.argv[4], sys.argv[5]
now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
lines = [
    "# AT1b harness cron status",
    "",
    "_Generated by `scripts/at1b-harness-status.sh --write-report`. Read-only; no PATCH._",
    "",
    f"checked_at_utc: `{now}`",
    "",
    "| Role | ID | enabled | last_run_at | next_run_at |",
    "|------|----|---------|-------------|-------------|",
]
for r in rows:
    lines.append(
        f"| {r['label']} | `{r['id']}` | {r.get('enabled')} | {r.get('last_run_at')} | {r.get('next_run_at')} |"
    )
lines += [
    "",
    "Expected cadence: supply `0 7 * * *` UTC, poll `0 18 * * *` UTC.",
    f"Default IDs: supply `{supply_id}`, poll `{poll_id}`.",
    "",
]
path.write_text("\n".join(lines), encoding="utf-8")
print(f"==> wrote {path}")
PY
fi

exit "$STATUS_RC"
