#!/usr/bin/env bash
# Prepare a Cloud Agent sandbox (Codex Cloud, Claude Code Cloud, Cursor Cloud).
# Installs optional CLIs, aliases common secret env names, runs agent-verify if present.
# Never prints secret values.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_ALIAS_FILE="${AGENT_ENV_ALIAS_FILE:-$HOME/.agent/env-aliases.sh}"
SKIP_CLI_INSTALL="${AGENT_SKIP_CLI_INSTALL:-0}"
FORCE_CLI_INSTALL="${AGENT_FORCE_CLI_INSTALL:-0}"
CLI_PACKAGES="${AGENT_CLI_PACKAGES:-opencode-ai @openai/codex @anthropic-ai/claude-code}"

ensure_node() {
  if command -v npm >/dev/null 2>&1; then
    return 0
  fi
  if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends nodejs npm git ca-certificates curl
    rm -rf /var/lib/apt/lists/*
    return 0
  fi
  echo "npm not found; install Node.js manually or set AGENT_SKIP_CLI_INSTALL=1" >&2
  return 1
}

install_clis() {
  if [[ "$SKIP_CLI_INSTALL" == "1" ]]; then
    echo "Skipping CLI install (AGENT_SKIP_CLI_INSTALL=1)"
    return 0
  fi
  ensure_node
  if [[ "$FORCE_CLI_INSTALL" == "1" ]] || ! command -v codex >/dev/null 2>&1; then
    # shellcheck disable=SC2086
    npm install --global $CLI_PACKAGES
    hash -r 2>/dev/null || true
  fi
}

write_env_aliases() {
  mkdir -p "$(dirname "$ENV_ALIAS_FILE")"
  cat >"$ENV_ALIAS_FILE" <<'ALIASES'
# Generated by setup-cloud-agent-env.sh — no literal secrets stored here.
if [ -z "${MINIMAX_API_KEY:-}" ] && [ -n "${minimax_api_key:-}" ]; then export MINIMAX_API_KEY="$minimax_api_key"; fi
if [ -z "${MINIMAX_API_KEY:-}" ] && [ -n "${MMINIMAX_API_KEY:-}" ]; then export MINIMAX_API_KEY="$MMINIMAX_API_KEY"; fi
if [ -z "${OPENROUTER_API_KEY:-}" ] && [ -n "${openrouter_api_key:-}" ]; then export OPENROUTER_API_KEY="$openrouter_api_key"; fi
if [ -z "${OPENROUTER_API_KEY:-}" ] && [ -n "${openrouter_api:-}" ]; then export OPENROUTER_API_KEY="$openrouter_api"; fi
if [ -z "${OPENAI_API_KEY:-}" ] && [ -n "${openai_api_key:-}" ]; then export OPENAI_API_KEY="$openai_api_key"; fi
if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -n "${anthropic_api_key:-}" ]; then export ANTHROPIC_API_KEY="$anthropic_api_key"; fi
if [ -z "${GEMINI_API_KEY:-}" ] && [ -n "${gemini_api_key:-}" ]; then export GEMINI_API_KEY="$gemini_api_key"; fi
if [ -z "${GH_TOKEN:-}" ] && [ -n "${github_token:-}" ]; then export GH_TOKEN="$github_token"; fi
ALIASES
  chmod 0600 "$ENV_ALIAS_FILE"
}

source_aliases_in_shell() {
  # shellcheck source=/dev/null
  [[ -f "$ENV_ALIAS_FILE" ]] && . "$ENV_ALIAS_FILE"
}

report_presence() {
  local name
  for name in MINIMAX_API_KEY OPENAI_API_KEY ANTHROPIC_API_KEY GEMINI_API_KEY OPENROUTER_API_KEY GH_TOKEN; do
    if [[ -n "${!name:-}" ]]; then
      echo "env: $name=set"
    else
      echo "env: $name=missing"
    fi
  done
  for cmd in git gh node npm codex claude opencode; do
    if command -v "$cmd" >/dev/null 2>&1; then
      echo "cli: $cmd=$(command -v "$cmd")"
    else
      echo "cli: $cmd=missing"
    fi
  done
}

main() {
  echo "==> setup-cloud-agent-env (root=$ROOT)"
  install_clis
  write_env_aliases
  source_aliases_in_shell
  report_presence
  if [[ -x "$ROOT/scripts/agent-verify.sh" ]]; then
    echo "==> running agent-verify.sh"
    (cd "$ROOT" && bash scripts/agent-verify.sh) || echo "WARN: agent-verify failed (configure VERIFY_L0/L1)"
  else
    echo "skip: scripts/agent-verify.sh not found"
  fi
  echo "==> To load aliases in current shell: . $ENV_ALIAS_FILE"
}

main "$@"
